""" "2022-06-19 09:23:14.066301"

Revision ID: d85906452f14
Revises: 72dba5f82c5e
Create Date: 2022-06-19 09:23:15.796089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd85906452f14'
down_revision = '72dba5f82c5e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
